.github/workflows/sync-template.yml, setup.sh
- Default to using GITHUB_TOKEN instead of PERSONAL_ACCESS_TOKEN if it is not there
- Add setup option to disable template syncing
- Add setup option to remove setup script
=> [Feature] Making PAT optional and adding stuff to setup script

.prettierignore
Fixes failing lint CI in #28
Ref: #23
=> Ignore {{}} syntax in template/CITATION.cff Linting

setup.js, template/CITATION.cff
As discussed in #23, I rewrote the code using Node.js and optimized it for all platforms using platform-independent methods built into Node.js. This has no dependencies and requires nothing but `node` to be installed (I used v20.11.0 for this, but since there is a deprecation issue, `rmSync` may not work on older versions. But it's easily resolvable). It does pretty much the same as the original `.sh` file. HOWEVER, I've noticed that the `CITATION.cff` file doesn't work properly with the placeholder replacement algorithm, due to how {{PROJECT_NAME}} and {{NAME}} placeholders are formatted in it, so I had to fix that as well. (changed the template). Honestly, I'm not very proud of how I wrote this, so any feedback or criticism is much appreciated. I hope this code works for you!
- Related …
=> Platform Compatibility

.github/workflows/test-worker.yml, README.md
Implement testing
- Closes #26 
- Related Issue #23 
- Related PR #28 
=> Testing node

babel.config.cjs, dist/error.js, dist/io-util.js, dist/setup.js, dist/types.js, eslint.config.mjs, package-lock.json, package.json, src/error.ts, src/io-util.ts, src/setup.ts, src/types.ts, tests/io-util.test.ts
- Add babel
- Add jest
- Testing for substituting {{.+}} in files
- Related Issue #26 
=> Testing substituing file content

dist/setup.js, src/setup.ts
This patch fixes the string for asking for the repository name by actually formatting the previously passed "username" into "$username" and making the parenthesis wrap the url.
=> fix: Format asking for repository name with username

dist/setup.js, src/setup.ts
This patch fixes #58 by force deleting files and directories that would only exist if development was carried out. Adding -f or force will suppress any "not found" errors. Examples of development-only include `node_modules/` and `.eslintcache`.
Closes #58
Ref: #58
=> fix: Rm with -f for development-only files and dirs

dist/parser.js, dist/resolver.js, dist/setup.js, dist/term.js, src/parser.ts, src/resolver.ts, src/setup.ts, src/term.ts, src/types.ts
This PR allows default values to be resolved from system git
- Closes #63 
=> feat: Automatically resolve git details

.gitignore, .goreleaser.yml, Makefile, cmd/root.go, package-lock.json
- Name changing artifacts
- Related Issue #75
=> fix: Name change artifacts

.goreleaser.yml, cmd/man.go, cmd/root.go, cmd/utils/string.go, cmd/utils/string_test.go, go.mod, go.sum
- Provide man pages
- Update goreleaser configs
- Related Issue #75
=> feat: Update releaser configs

.goreleaser.yml
This fixes creating the binary at /bin/waku/waku instead of the proper /bin/waku. This is dumb. I've already pushed this fix to the AUR.
=> fix: Creating a dir instead of a bin

.github/workflows/release.yml, .goreleaser.yml, Dockerfile, Dockerfile.release
- Do not rebuild within docker for release
- Skip `latest` and `v{major}` for prereleases
- Build for `arm64` as well
- Use docker manifests to group arm64 and amd64 images
=> ci: Docker release improvements

cmd/global/version.go, cmd/man.go, cmd/root.go, docs/install.md, go.mod, go.sum
This fixes failing manpage installs
=> fix: Manpage generation cmd not piping to stdout

cmd/global/version.go, cmd/root.go, www/docs/configuration/introduction.md, www/docs/install.md
The log.Fatal() can be removed because for .Execute() to reuturn an error means that that error is recoverable and the default CLI error msg has been thrown, so this fatal log is redundant.
The log.Fatal() can be removed because for .Execute() to reuturn an
error means that that error is recoverable and the default CLI error msg
has been thrown, so this fatal log is redundant.
=> fix: Remove extra logging on error

internal/log/warning.go
- Make warns go to stderr not stdout
=> feat: Warns should go to stderr

cmd/commands/new.go, cmd/options/new.go, internal/git/check.go, internal/license/store.go, internal/license/types.go, internal/types/cli.go, pkg/version/version.go, www/docs/blog/posts/2024-10-08-waku-v0.6.0.md, www/docs/configuration/introduction.md, www/docs/deprecations.md, www/docs/install.md
- Deprecate `--repo` for `--source`
- Fix a bug with license when passing `repo|source` flag
- Closes #161
=> feat: Support using local directory as template

cmd/commands/new.go, pkg/version/version.go, www/docs/configuration/introduction.md, www/docs/install.md
=> fix: Only license is templated

.github/workflows/release.yml
It has happened far too many times were I tagged and released a new version while forgetting to update the version in-code.
This check will just help to ensure that it always is updated before it even builds the release bins.
=> ci: Check that tags are updated before release

cmd/commands/new.go, cmd/options/new.go
Adds the `--no-license` and `-L` flags that are mutually exclusive with the `--license` and `-l` flags.
- Closes #168
=> feat: Implement --no-license/-L flag

go.mod, go.sum, internal/config/config.go, internal/template/parse_config.go, internal/types/clean_string.go, internal/types/clean_string_test.go, internal/types/color.go, internal/types/color_test.go, internal/types/regex.go, internal/types/regex_test.go, internal/types/set.go, internal/types/set_test.go, internal/types/value_guard.go, internal/types/value_guard_test.go, pkg/config/ignore.go, pkg/config/includes.go, pkg/config/prompts.go
This is in response to `gopkg.in/yaml.vX` being archived and marked as unmaintained [1]. Since we are already using goccy's `go-json`, it makes sense to migrate over to goccy's `go-yaml` as well.
[1]: https://github.com/go-yaml/yaml/commit/944c86a7d29391925ed6ac33bee98a0516f1287a
=> feat: Migrate gopkg.in/yaml -> goccy/go-yaml 

cmd/commands/new.go
.License and .Spdx are unset if `-L/--no-license` is set
=> fix: .License & .Spdx do not exist if -L is set
