- .github/workflows/sync-template.yml
> fix: Not skipping on main

- README.md
> feat: Add acknowledgement

- .github/workflows/sync-template.yml
- Add PAT requirement to fix failing updating workflows
> fix: Add PAT to enable updating workflows

- .github/labeler.yml
- .github/settings.yml
- .github/workflows/labeler.yml
- Add automatic labeling
- Add CI label
> Ci: Add automatic labeling

- .github/workflows/first-time-contributor.yml
- Add workflow to greet new contributors
> ci: Add first time contributor greeting

- .github/labeler.yml
> fix: Follow labeler v5 docs

- .github/workflows/labeler.yml
- Add instructions for setting permissions
> doc: Add instructions if missing permissions

- README.md
- setup.sh
- Add a setup script
- Update documentation
> Feat: setup script

- .github/workflows/test-worker.yml
> Feat: Add test suite

- setup.sh
- Assignees are note replaced correctly by setup.sh
- Closes #14
> fix: Wrong replacement

- CITATION.cff
Bump version to 1.8.0
- Closes #
> Bump version to 1.8.0

- .github/labeler.yml
- .github/workflows/labeler.yml
- template/.github/labeler.yml
- template/.github/workflows/labeler.yml
- Fix failing CI on PRs from forks by change "on" to `pull_request_target` instead of `pull_request`
- Fix CI applying Documentation label to non-workflows
- Related PR #28 
> Fix CI labeler failing on PRs from forks and applying wrong labels

- README.md
Update outdated setup command
- Closes #
> Update setup command to use dist

- dist/error.js
- dist/io-util.js
- dist/setup.js
- tsconfig.json
Update typescript compiler settings
- Closes #
> Fix transpiled js cant run with Node.Js

- CITATION.cff
Bump to v1.9.0
- Related PR #28 
- Related PR #30 
- Related Issue #26 
- Related Issue #23 
> chore(ver): Bump version to 1.9.0-alpha.1

- CITATION.cff
- dist/setup.js
- src/setup.ts
- template/.github/ISSUE_TEMPLATE/1-bug-report.md
- template/.github/ISSUE_TEMPLATE/2-failing-test.md
- template/.github/ISSUE_TEMPLATE/3-docs-bug.md
- template/.github/ISSUE_TEMPLATE/4-feature-request.md
- template/.github/ISSUE_TEMPLATE/5-enhancement-request.md
- template/.github/ISSUE_TEMPLATE/6-security-report.md
- template/.github/ISSUE_TEMPLATE/7-question-support.md
- Fix moving files error
- Added more dev files to cleanup
- Fix issue template assignees replacement
- Remove `.templatesyncignore` leading newline
- Closes #
> Fix some setup errors

- .github/ISSUE_TEMPLATE/1-bug-report.md
- .github/ISSUE_TEMPLATE/2-failing-test.md
- .github/ISSUE_TEMPLATE/3-docs-bug.md
- .github/ISSUE_TEMPLATE/4-feature-request.md
- .github/ISSUE_TEMPLATE/5-enhancement-request.md
- .github/ISSUE_TEMPLATE/6-security-report.md
Fix project issue template links not updated
- Closes #
> Project issue template links not updated

- dist/setup.js
- src/setup.ts
- Lightly validate email against RegExp pattern
- Trim leading and trailing whitespace
- Closes #43 
> Validating input

- CITATION.cff
- dist/io-util.js
- dist/setup.js
- src/io-util.ts
- src/setup.ts
- src/types.ts
- template/.github/ISSUE_TEMPLATE/1-bug-report.md
- template/.github/ISSUE_TEMPLATE/2-failing-test.md
- template/.github/ISSUE_TEMPLATE/3-docs-bug.md
- template/.github/ISSUE_TEMPLATE/4-feature-request.md
- template/.github/ISSUE_TEMPLATE/5-enhancement-request.md
- template/.github/ISSUE_TEMPLATE/6-security-report.md
- template/.github/ISSUE_TEMPLATE/7-question-support.md
- tests/io-util.test.ts
- Comment previous streaming attempt
- Add configuring assignees
- Update template issue templates
- Closes #44 
> Configuring assignees

- CITATION.cff
- dist/setup.js
- src/setup.ts
- Generate src and tests direcotry
> Generate src and test directory

- CITATION.cff
- dist/setup.js
- src/setup.ts
It is hard to tell the looping behavior with Promise passed into `forEach`.
This makes it more explicit as a synchronous operation
- Closes #
> Fix Sync/Async ambiguity

- CITATION.cff
- dist/setup.js
- src/setup.ts
Doing it synchronously seemed too slow
- Closes #
> Write to template/ asynchronously

- CITATION.cff
- dist/setup.js
- src/setup.ts
Cleanup `.templatesyncignore` file.
- Closes #
> Cleanup syncignore

- dist/setup.js
- src/setup.ts
Fixes file content not being replaced
- Closes #61
> fix: File content not being replaced

- CITATION.cff
- dist/io-util.js
- src/io-util.ts
- tests/io-util.test.ts
This PR fixes the broken github repo URLs
- Closes #65 
> fix: {{REPOSITORY}} not following <org>/<repo>

- .github/workflows/linting.yml
- .github/workflows/test-worker.yml
- cmd/commands/root.go
- cmd/commands/version.go
- cmd/commands/version_test.go
- cmd/global/version.go
- cmd/global/version_test.go
- cmd/helpers/testing.go
- cmd/helpers/testing_test.go
- cmd/options/options.go
- cmd/options/root.go
- cmd/root.go
- cmd/root_test.go
- cmd/utils/types/value_guard.go
- cmd/utils/types/value_guard_test.go
- go.mod
- go.sum
- main.go
- Added version command
- Added CLI options and flags
- Related Issue #75 
- Related Issue #26 
> feat: A simple CLI implementation

- cmd/options/options.go
- cmd/options/root.go
- cmd/root.go
- cmd/utils/file.go
- Adding cache directory option
- Creating cache dir if it does not already exist
> feat: Add caching dir and resolving option

- cmd/commands/version.go
- cmd/commands/version_test.go
- cmd/helpers/testing_test.go
- cmd/root.go
- cmd/root_test.go
- cmd/utils/types/value_guard.go
- cmd/utils/types/value_guard_test.go
> style: Standardize string casing

- cmd/commands/new.go
- cmd/commands/new_repo.go
- Add new command alias for "new"
- Related Issue #75 
> feat: Add "new repo" command alias for "new"

- cmd/commands/check.go
- cmd/commands/new.go
> fix: errors not returning status 1

- cmd/config/skip.go
> fix: Wrong error msg

- cmd/global/version.go
> chore: bump version to 0.1.0

- .github/workflows/release.yml
- Install choco before running goreleaser
> ci: Install choco in CI

- .github/workflows/release.yml
- Fix lacking permissions in github docker (GHCR) push
> ci: Use PAT for logging into ghcr

- .github/workflows/release.yml
Oops!
I saved the secret key under a different name.
I'll manually push to the AUR this time, but there should be no issue next time using
goreleaser in CI.
> ci: Fix missing AUR env key

- .goreleaser.yml
- Broken download url template
- Ensure dirs exist with (mkdir -p)
- Random quote
> ci: fix aur MAKEPKG

- .goreleaser.yml
Oops, another thing i forgot to update 😭 
> ci: Wrong package name template -> waku

- docs/install.md
Fix docker wrong install command
> docs: Wrong docker user caffeine -> caffeinec

- .goreleaser.yml
Fix broken image urls in choco and docker images
> ci: Use raw usercontent image url

- cmd/config/template.go
- cmd/options/global.go
- cmd/utils/string.go
> typo: Fix some simple typos

- .github/workflows/linting.yml
- .github/workflows/release.yml
- .github/workflows/test-worker.yml
Use stable go version
- Closes #
> ci: Use stable version

- .goreleaser.yml
The review process is slow and causing release CI to fail, I will consider pushing a scoop instead of choco; I'm removing choco for now.
What a headache.
> ci: Remove choco releases

- .github/PULL_REQUEST_TEMPLATE.md
- cmd/global/version.go
> fix: bump version number accordingly

- cmd/global/version.go
> fix: version number

- .goreleaser.yml
- cmd/global/version.go
Fix failing releases on snap
- Closes #
> fix: Snap confinement classic -> strict

- .goreleaser.yml
So I do not forget to release and accidentally break the AUR or release-compiled bin dependent releases
> ci: Publish release instead of draft

- CONTRIBUTING.md
Realized CONTRIBUTING was still out of date
> docs: Update CONTRIBUTING

- .goreleaser.yml
- cmd/global/version.go
Revert confinement change for snap packages due to git not being accessible
- Related Issue #122
> revert: Git not found in path on SNAP store

- .github/workflows/release.yml
- .goreleaser.yml
- cmd/global/version.go
- docs/install.md
Waku is now installable on scoop
> ci: Release Waku on Scoop

- .github/workflows/release.yml
> ci: set up cosign before build process

- .github/workflows/release.yml
So that cosign can sign the binaries properly
> ci: Provide id-token write permission

- .github/workflows/release.yml
- .goreleaser.yml
I will pause releasing on snapcraft until #122 is resolved.
- Related Issue #122
> revert: Pause snapcraft releases

- cmd/license/license_test.go
- licenses/license.json
improving license.json tests and fixing some errors
> fix: Invalid 0BSD filename and improving license tests

- cmd/global/version.go
- cmd/license/store.go
- cmd/options/new.go
- docs/install.md
Use tag instead of main branch
- Closes #133
> feat: Use the v tag instead of main

- cmd/global/version.go
- template/template.json
- www/docs/install.md
- fix issues regarding the prompts for simple-github style
> fix: Fixup simple GitHub style

- cmd/commands/healthcheck.go
- cmd/commands/root.go
- add healthcheck command
- Related Issue #139
> feat: Add healthcheck command

- internal/log/debug.go
- internal/log/error.go
- internal/log/verbose.go
- internal/log/warning.go
> fix: Remove extra space after prefix

- .github/workflows/linting.yml
- .github/workflows/release.yml
- .github/workflows/test-worker.yml
- cmd/commands/healthcheck.go
> ci: Cache golang builds

- www/docs/configuration/fields/prompts.md
- www/docs/configuration/templates.md
- www/mkdocs.yml
> docs: Add docs for the default template values

- cmd/cleanup/cleanup.go
- cmd/commands/check.go
- cmd/commands/healthcheck.go
- cmd/commands/new.go
- cmd/commands/version.go
- cmd/helpers/testing.go
- cmd/man.go
- cmd/root.go
- internal/errors/errors.go
- internal/log/debug.go
- internal/log/error.go
- internal/log/log.go
- internal/log/print.go
- internal/log/verbose.go
- internal/log/warning.go
- pkg/version/version.go
- www/docs/configuration/introduction.md
- www/docs/install.md
- Make cmd's return `*errors.WakuError`
- Fixup some logging
- Have `Print` operations respect `log.LogLevel`
- Closes #155
> feat: Improve error handling

- www/docs/blog/posts/2024-10-12-waku-v0.7.0.md
> docs: Add v0.7 docs

- .github/workflows/release.yml
- .goreleaser.yml
- www/docs/install.md
Not considered breaking change as Waku was never publicly available on chocolatey
> docs: Remove waku on chocolatey

- internal/utils/templater.go
- internal/utils/templater_test.go
- pkg/version/version.go
- www/docs/configuration/introduction.md
- www/docs/install.md
+ Resolves issue of HTML comments being removed.
+ Now errors on missing keys
- Closes #
> feat: improve template parsing

- .prettierignore
- www/docs/blog/posts/2024-10-08-waku-v0.6.0.md
- www/docs/blog/posts/2024-10-12-waku-v0.7.0.md
- www/docs/blog/posts/2025-01-19-waku-v0.8.0.md
- www/docs/configuration/quick-start.md
- www/docs/configuration/templates.md
- www/docs/deprecations.md
- www/docs/install.md
- www/docs/overrides/home.html
- www/docs/overrides/main.html
+ Add v0.8.0 blog
+ Prettier formatting in docs
+ fixing some broken links
- Closes #
> docs: Add waku v0.8.0 blog

- cmd/commands/new.go
- cmd/options/new.go
- internal/template/prompting.go
- Do not force name to lowercase
+ Allow skipping replacing spaces with hyphens
> feat: Improve project naming flexibility

- www/docs/static/schema.json
In preparation of allowing yaml configs to be more modular
> feat: Allow additional properties in unknown types

- www/docs/install.md
Looks like it somehow got over-indented and it broke the rendering...
> docs: Fix broken sh example

- cmd/options/new.go
- internal/types/clean_string.go
- internal/types/permissive_string.go
- internal/types/permissive_string_test.go
- internal/utils/string.go
- internal/utils/string_test.go
- pkg/config/prompts.go
Let's have levels to how strict and controlled I want the dynamic user-facing strings to be.
As of right now, I see value in allowing newlines for prompt asks.
> feat(UX): allow permissive strings in ask
